### ISSUE TITLE
[BUG] Kashtira Ogre does not activate the banish effect

### ISSUE THREAD

**Issue by VaHReX** [Fluorohydride/ygopro-scripts#2682]
When an attack is declared with Kashtira Ogre, its effect is activated, allowing you to look at up to 5 cards on top of the opponent's deck, then you can take 1 and banish it face down, that banishing effect is not activated.

ID: 94392192

**Comment by mercury233** [comment]
can't reproduce

**Comment by DaruKani** [comment]
Can I ask here about "Kashtira Ogre" case
But first let's give more Infomation about this case.
1 It happen on MDPro3 "**solo mode**" only!
2 It happen to ARGStar (from Super-pre) too.
3 these 2 case work fine in "**Online mode**" (Super-pre server)

The question is :
What is differnt between Solo mode of MDPro and Online mode?

**Comment by mercury233** [comment]
> The question is : What is different between Solo mode of MDPro and Online mode?

Generally the clients (YGOPro1, MDPro3 etc.) and servers of YGOPro (EDOPro excluded) will be using the same ocgcore and scripts, but sometimes some client (or user) may forgot to update one of them on release, and it will encounter error, because the new version of ocgcore need new scripts, vice versa.
Another problem is the clients will not receive updates daily, but some servers will, so some bugs will be fixed on those servers first.
